### ISSUE TITLE
Cannot load

### ISSUE THREAD

**Issue by arik123** [ElegantMonkey/tf2-metalbot#1]
https://www.dropbox.com/s/apkemiz4w5oez72/error.PNG?dl=0

**Comment by ekisu** [comment]
You need to build the TypeScript files. Run `build.bat` then `run.bat`.

**Comment by arik123** [comment]
i did

**Comment by ekisu** [comment]
Then try running `node src\main.js` (not `main.ts`) on the same folder as the config.json.

**Comment by AlexLKW** [comment]
There's no main.js in the src folder after running the build.bat

**Comment by ekisu** [comment]
Are Node binaries correctly installed, and in the PATH? Try running `npm` in a cmd window and see if anything happens.

**Comment by AlexLKW** [comment]
After running the Build.bat, only "node_modules" was created and still nothing called "main.js" in the src folder.

**Comment by ekisu** [comment]
Try with the last commit, should work now.
