### ISSUE TITLE
Del

### ISSUE THREAD

**Issue by John677** [ElegantMonkey/tf2-metalbot#2]
Did everything as in the description, 300 items, crafting not working((

**Comment by ekisu** [comment]
The script only convert between metal currencies (refined/reclaimed/scrap).

It doesn't try to smelt (duplicate) weapons into metal, as, if I recall correctly, there's no single, surefire way to know whether a weapon is unique, or is a strange/KS version, so it could mistakenly smelt strange weapons. Sorry if this is what you wanted.

**Comment by John677** [comment]
And you can write code to melt any weapon? Not important  weapon is unique, or is a strange/KS version. I just don't have such weapons, I'm not scared if something goes wrong

**Comment by ekisu** [comment]
This is a very specific usecase, really. I might look again if there's a way to differentiate weapons, so that it only smelts unique ones, but smelting anything is probably out of question.
