### ISSUE TITLE
guard

### ISSUE THREAD

**Issue by ande2517** [ElegantMonkey/tf2-metalbot#4]
Hello! Autologin with Steam guard code does not work?

**Comment by ekisu** [comment]
Seems to be working for me (remember login). Did you get any errors?

**Comment by ande2517** [comment]
I'm talking about automatic input of steam guard code. Like realized in SteamBot using .mafile from SDA. I didn't understand is it possible to do.

**Comment by ekisu** [comment]
It might be possible - SteamBot uses geel's [SteamAuth](https://github.com/geel9/SteamAuth) to generate a Steam Guard code, which seems to have a [Node](https://github.com/winauth/SteamAuth) implementation/port (it's 2 years old though, I don't know if it still works).  I might look at this when I have more free time.

**Comment by ande2517** [comment]
I'll be very grateful

**Comment by AlexLKW** [comment]
You have to root the phone and get the identity secret to get the auth code

**Comment by ekisu** [comment]
As of 328d1f2, you can use the sharedSecret field (which can be found inside .mafiles, I think, and inside the Steam Guard file on rooted phones) to avoid the Steam Guard prompt.

However, this won't make the login automatic when the loginKey expires, as you would still need to input your username and password again. The only way to avoid that, I think, is by storing the password in plain text in the config, which is something I don't think is a good idea.

How does other applications (like SteamBot) handle this?
